services:
    web:
        build: .
        ports:
            - "${RAILS_PORT}:${RAILS_PORT}"
        volumes:
            - .:/app
            - bundle_cache:/usr/local/bundle
        environment:
            - RAILS_PORT=${RAILS_PORT}
            - MYSQL_HOST=db
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: db
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - db

volumes:
    db_data:
    bundle_cache:
